[GENERAL]
# 通用设置
SIMILARITY_MEASURE = "cosine" # 相似度度量方法，可选 "cosine" (余弦相似度) 或 "dot" (点积)。
KEEP_ALIVE = "5m" # Ollama 模型在内存中保持加载状态的时间 (若要永久保持，请使用 "-1m" 而不是 -1)。

[MODELS.OPENAI]
# OpenAI 模型设置
API_KEY = "" # 您的 OpenAI API 密钥。

[MODELS.GROQ]
# Groq 模型设置
API_KEY = "" # 您的 Groq API 密钥。

[MODELS.ANTHROPIC]
# Anthropic 模型设置
API_KEY = "" # 您的 Anthropic API 密钥。

[MODELS.GEMINI]
# Gemini 模型设置
API_KEY = "" # 您的 Gemini API 密钥。

[MODELS.CUSTOM_OPENAI]
# 自定义 OpenAI 兼容模型设置
API_KEY = "" # 您的 API 密钥。
API_URL = "" # 您的 API URL。
MODEL_NAME = "" # 您要使用的模型名称。

[MODELS.OLLAMA]
# Ollama 模型设置
API_URL = "" # Ollama API URL - 例如：http://host.docker.internal:11434

[MODELS.DEEPSEEK]
# DeepSeek 模型设置
API_KEY = "" # 您的 DeepSeek API 密钥。

[MODELS.LM_STUDIO]
# LM Studio 模型设置
API_URL = "" # LM Studio API URL - 例如：http://host.docker.internal:1234

[API_ENDPOINTS]
# API 端点设置
SEARXNG = "" # SearxNG API URL - 例如：http://localhost:32768
